# Generated by Django 5.1.6 on 2026-05-16 22:24

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duenos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Edad', models.IntegerField()),
                ('Correo', models.EmailField(max_length=50, unique=True)),
                ('Telefono', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Dueño',
                'verbose_name_plural': 'Dueños',
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('IDEspecialidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='razas/')),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
            },
        ),
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('IDDoctor', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Componentes.especialidades')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('IdMascota', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('dueno', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Componentes.duenos')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Componentes.raza')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
        migrations.CreateModel(
            name='Historias',
            fields=[
                ('IDHistoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_historia', models.CharField(max_length=10, unique=True)),
                ('Descripcion', models.TextField(max_length=500)),
                ('Fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Componentes.doctores', verbose_name='Doctor')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Componentes.mascotas', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historias',
                'ordering': ['-Fecha'],
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('IdCita', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateTimeField(verbose_name='Fecha y Hora de la Cita')),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo de la Cita')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas del Doctor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Componentes.doctores', verbose_name='Doctor')),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Componentes.duenos', verbose_name='Dueño')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Componentes.mascotas', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_cita'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=50)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('veterinario', 'Veterinario'), ('recepcionista', 'Recepcionista')], default='recepcionista', max_length=20)),
                ('telefono', models.CharField(blank=True, default='', max_length=15)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
