# Generated by Django 5.1.6 on 2025-03-06 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Edad', models.PositiveIntegerField(verbose_name='1')),
                ('Correo', models.EmailField(max_length=30, unique=True)),
                ('Telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('IDEspecialidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=30)),
                ('Foto', models.FileField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdUsuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('IDDoctor', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(blank=True, max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Componentes.especialidades')),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('IdMascota', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('dueño', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Componentes.duenos')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Componentes.raza')),
            ],
        ),
        migrations.CreateModel(
            name='Historias',
            fields=[
                ('IDHistoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_historia', models.CharField(max_length=10, unique=True)),
                ('Descripcion', models.TextField(max_length=500)),
                ('Fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Componentes.doctores', verbose_name='nombre')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Componentes.mascotas', verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historias',
            },
        ),
    ]
