# Generated by Django 5.1.6 on 2025-03-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Componentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascotas',
            options={'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AlterModelOptions(
            name='raza',
            options={'verbose_name': 'Raza', 'verbose_name_plural': 'Razas'},
        ),
        migrations.RemoveField(
            model_name='raza',
            name='Foto',
        ),
        migrations.AddField(
            model_name='raza',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='razas/'),
        ),
    ]
