# Generated by Django 5.1.6 on 2026-05-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Componentes', '0002_fix_usuario_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotas',
            name='correo',
        ),
        migrations.AddField(
            model_name='mascotas',
            name='especie',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], default='perro', max_length=20),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='otra_especie',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Especie (otro)'),
        ),
    ]
