# Generated by Django 5.1.6 on 2025-03-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Componentes', '0002_alter_mascotas_options_alter_raza_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raza',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='duenos',
            name='Correo',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='duenos',
            name='Edad',
            field=models.IntegerField(),
        ),
    ]
