# Generated by Django 5.1.6 on 2025-03-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Componentes', '0003_rename_nombre_raza_nombre_alter_duenos_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascotas',
            old_name='dueño',
            new_name='dueno',
        ),
        migrations.AlterField(
            model_name='duenos',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
    ]
