# Generated by Django 5.1.6 on 2026-05-29 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Componentes', '0004_usuario_is_verified_verificationtoken'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='componentes_usuario',
        ),
    ]
